McvOnlineTicariOtomasyon/Controllers/CariController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using McvOnlineTicariOtomasyon.Models.siniflar;

namespace McvOnlineTicariOtomasyon.Controllers
{
    
    public class CariController : Controller
    {
        // GET: Cari
        Context c = new Context();
        public ActionResult Index()
        {
            var değerler = c.Carilers.Where(x=>x.Durum == true).ToList();
            return View(değerler);
        }
        public ActionResult YeniCari()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniCari(Cariler p)
        {
            p.Durum = true;
            c.Carilers.Add(p);
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult CariSil(int id)
        {
            var car = c.Carilers.Find(id);
            car.Durum = false;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult CariGetir(int id )
        {
            var cari = c.Carilers.Find(id);
            return View("CariGetir",cari);
        }
        [HttpPost]
        public ActionResult CariGüncelle(Cariler p)
        {
            if(!ModelState.IsValid)
            {
                return View("CariGetir");
            }
            var cari = c.Carilers.Find(p.CariId);
            cari.CariAd = p.CariAd;
            cari.CariSoyad = p.CariSoyad;
            cari.CariSehir = p.CariSehir;
            cari.CariMail = p.CariMail;
            c.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult MüsteriSatis(int id)
        {
            var degerler = c.SatisHarekets.Where(x => x.Cariid == id).ToList();
            var mus = c.Carilers.Where(x => x.CariId == id).Select(y => y.CariAd + " " + y.CariSoyad).FirstOrDefault();
            ViewBag.must = mus;
            return View(degerler);

        }
    }
}

McvOnlineTicariOtomasyon/Views/Cari/CariGetir.cshtml
@model McvOnlineTicariOtomasyon.Models.siniflar.Cariler
@{
    ViewBag.Title = "CariGetir";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Cari Güncelleme Ekranı</h2>
<br />
@using(Html.BeginForm("CariGüncelle","Cari",FormMethod.Post))
            {
<div class="form-group">
    @Html.HiddenFor(x => x.CariId)
    @Html.LabelFor(x => x.CariAd)
    @Html.TextBoxFor(x => x.CariAd, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariAd, "", new { @style = "color:red" })
    <br />
    @Html.LabelFor(x => x.CariSoyad)
    @Html.TextBoxFor(x => x.CariSoyad, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariSoyad, "", new { @style = "color:red" })
    <br />
    @Html.LabelFor(x => x.CariSehir)
    @Html.TextBoxFor(x => x.CariSehir, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariSehir, "", new { @style = "color:red" })
    <br />
    @Html.LabelFor(x => x.CariMail)
    @Html.TextBoxFor(x => x.CariMail, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CariMail, "", new { @style = "color:red" })
    <br />
    <button class="btn btn-default" style="background-color:yellowgreen">Güncelle</button>
</div>
            }

McvOnlineTicariOtomasyon/Views/Cari/Index.cshtml
@using McvOnlineTicariOtomasyon.Models.siniflar;
@model List<Cariler>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Cariler</h2>
<br />
<table class="table table-striped">
    <tr>
        <th>Cari ID</th>
        <th>Ad</th>
        <th>Soyad</th>
        <th>Şehir</th>
        <th>Mail</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Detaylar</th>
    </tr>
    @foreach(var x in Model)
            {
                <tr>
                    <td>@x.CariId</td>
                    <td>@x.CariAd</td>
                    <td>@x.CariSoyad</td>
                    <td>@x.CariSehir</td>
                    <td>@x.CariMail</td>
                    <td> <a href="/Cari/CariSil/@x.CariId"class="btn btn-danger">Sil</a></td>
                    <td> <a href="/Cari/CariGetir/@x.CariId"class="btn btn-warning">Güncelle</a></td>
                    <td> <a href="/Cari/MüsteriSatis/@x.CariId"class="btn btn-default"style="background-color:mediumslateblue">Satış Geçmişi</a></td>
                </tr>
            }
</table>
<a href="/Cari/YeniCari/" class="btn btn-info">Yeni Cari Ekle</a>

McvOnlineTicariOtomasyon/Views/Cari/MüsteriSatis.cshtml
@using McvOnlineTicariOtomasyon.Models.siniflar;
@model List<SatisHareket>
@{
    ViewBag.Title = "MüsteriSatis";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}

<br />
<h2>Departman Personel Satış</h2>
<br />
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Cari Adı : @ViewBag.must</li>
</ol>
<table class="table table-condensed">
    <tr>
        <th>Ürün</th>
        <th>Personel</th>
        <th>Fiyat</th>
        <th>Adet</th>
        <th>Toplam</th>
        <th>Tarih</th>
        <th>Yazdır</th>
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.Urun.UrunAd</td>
            <td>@x.Personel.PersonelAd @x.Personel.PersonelSoyad</td>
            <td>@x.Fiyat ₺</td>
            <td>@x.Adet</td>
            <td>@x.ToplamTutar ₺</td>
            <td>@x.Tarih</td>
            <td><a href="#" class="btn btn-default" style="background-color:dodgerblue">Yazdır</a></td>
        </tr>
    }
</table>

McvOnlineTicariOtomasyon/Views/Cari/YeniCari.cshtml
@model McvOnlineTicariOtomasyon.Models.siniflar.Cariler
@{
    ViewBag.Title = "YeniCari";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}
<br />
<h2>Yeni Cari Sayfası</h2>
<br />
<form class="form-group" method="post">
    @Html.LabelFor(x => x.CariAd)
    @Html.TextBoxFor(x => x.CariAd, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CariSoyad)
    @Html.TextBoxFor(x => x.CariSoyad, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CariSehir)
    @Html.TextBoxFor(x => x.CariSehir, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.CariMail)
    @Html.TextBoxFor(x => x.CariMail, new { @class = "form-control" })
    <br />
    
    <button class="btn btn-info">Kaydet</button>
</form>